### ISSUE TITLE
Deploying at Scale

### ISSUE THREAD

**Issue by Sicarus** [intuit/wasabi#54]
Is there a way one can deploy at scale using docker and linux?
I'm assuming this is not how intuit runs it in production, but would like to setup something similar with our own standalone mysql / cassandra instances. Is there any in depth guide one can read?
Thank you!

**Comment by tariqislam** [comment]
Hi Sicarus,

Glad you're thinking about deploying at scale! Right now we don't use docker to deploy. We don't have any deployment documentation, since this is usually specific to company needs and preferences, but perhaps we can start with the overall architecture diagram in our user guide: 

https://intuit.github.io/wasabi/v1/guide/index.html#overall-architecture

A couple of thoughts on the diagram:
- We broke our application into a web and app tier.
  - The web tier runs apache, performs SSL termination, and for the most part simply redirects the request to the app tier.
  - The app tier runs the wasabi app within Jetty.
  - As a thought, if you want to keep it simple, you can run both apache and jetty in the same machine.
- We have a Cassandra cluster that the app tier talks to.
- We use AWS RDS for hosting our MySQL instance.

If I may ask, what company are you working with to deploy Wasabi in prod? If need be, perhaps we can have more conversations.

Good luck!

Tariq
